export enum ChannelProviderEnum {
  WHATSAPP = 'WHATSAPP',
  FACEBOOK = 'FACEBOOK',
  EMAIL = 'EMAIL',
  WEBCHAT = 'WEBCHAT',
  INSTAGRAM = 'INSTAGRAM',
  WABA = 'WABA',
  PHONE = 'PHONE',
  SYSTEM = 'SYSTEM',
  INTERNAL = 'INTERNAL',
  ANNOTATION = 'ANNOTATION',
}
