// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { agendorCrmBlock } from '.'

export const agendorCrmBlockSchema = parseBlockSchema(agendorCrmBlock)
export const agendorCrmCredentialsSchema =
  parseBlockCredentials(agendorCrmBlock)
