// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { poliBlock } from '.'

export const poliBlockSchema = parseBlockSchema(poliBlock)
export const poliCredentialsSchema = parseBlockCredentials(poliBlock)
